name = "okane"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
licences = ["MIT"]
repository = { type = "github", user = "soulsam480", repo = "okane" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#

migrations_dir = "./src/app/db/migrations"
schemafile = "./src/app/db/schema.sql"


[dependencies]
gleam_stdlib = "~> 0.40.0"
wisp = "~> 1.2.0"
gleam_erlang = "~> 0.27.0"
mist = "~> 3.0.0"
gleam_http = "~> 3.7.0"
radiate = "~> 0.4.0"
dot_env = "~> 1.2.0"
glisten = "~> 6.0.0"
cake = "~> 2.0.1"
sqlight = "~> 0.9.1"
feather = ">= 1.2.0 and < 2.0.0"
decode = ">= 0.3.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0.0"
